import { analyzeIdeaWithOpenRouter } from "../services/openRouterService.js";
import Idea from "../models/Idea.js";
import PDFDocument from "pdfkit";

export const analyzeIdea = async (req, res) => {
  try {
    const { idea } = req.body;
    const userId = req.user.id;

    if (!idea) return res.status(400).json({ message: "Idea is required" });

    const analysis = await analyzeIdeaWithOpenRouter(idea);

    const savedIdea = await Idea.create({
      user: userId,
      idea,
      analysis,
    });

    res.status(201).json({ message: "Idea analyzed successfully", idea: savedIdea });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to analyze idea", error: err.message });
  }
};

export const getUserIdeas = async (req, res) => {
  try {
    const userId = req.user.id;
    const ideas = await Idea.find({ user: userId }).sort({ createdAt: -1 });
    res.json(ideas);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to fetch ideas", error: err.message });
  }
};

export const deleteIdea = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const idea = await Idea.findOneAndDelete({ _id: id, user: userId });
    if (!idea) return res.status(404).json({ message: "Idea not found" });

    res.json({ message: "Idea deleted successfully" });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to delete idea", error: err.message });
  }
};

export const saveIdea = async (req, res) => {
  try {
    const { idea, analysis } = req.body;
    const userId = req.user.id;

    if (!idea || !analysis)
      return res.status(400).json({ message: "Idea and analysis are required" });

    const newIdea = new Idea({ user: userId, idea, analysis });
    await newIdea.save();

    res.status(201).json({ message: "Idea saved successfully", idea: newIdea });
  } catch (err) {
    console.error("Error saving idea:", err);
    res.status(500).json({ message: "Failed to save idea", error: err.message });
  }
};

export const getIdeaById = async (req, res) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const idea = await Idea.findOne({ _id: id, user: userId });
    if (!idea) return res.status(404).json({ message: "Idea not found" });

    res.json(idea);
  } catch (err) {
    console.error("Error fetching idea by ID:", err);
    res.status(500).json({ message: "Failed to fetch idea", error: err.message });
  }
};

/* ✅ Updated In-Memory PDF Generation */
export const generatePitchDeck = async (req, res) => {
  try {
    const { idea, analysis } = req.body;

    if (!idea || !analysis) {
      return res.status(400).json({ message: "Idea and analysis are required" });
    }

    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(chunks);

      res.writeHead(200, {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${idea
          .replace(/\s+/g, "_")
          .slice(0, 50)}_PitchDeck.pdf"`,
      });
      res.end(pdfBuffer);
    });

    // --- PDF content ---
    doc.fontSize(28).fillColor("#4B0082").text("🚀 Startup Pitch Deck", { align: "center" });
    doc.moveDown(1.5);
    doc.fontSize(22).fillColor("#000").text(idea, { align: "center" });
    doc.moveDown(2);
    doc.fontSize(12).fillColor("#666").text("Generated using VentureLens AI", { align: "center" });

    const sections = [
      "Problem",
      "Solution",
      "Market Opportunity",
      "Business Model",
      "Competitive Advantage",
      "Revenue Strategy",
      "Technology Stack",
      "Future Vision",
    ];

    sections.forEach((section) => {
      doc.addPage();
      doc.fontSize(24).fillColor("#4B0082").text(section, { underline: true });
      doc.moveDown(1);
      doc.fontSize(14).fillColor("#000").text(analysis, { align: "left", lineGap: 6 });
    });

    doc.addPage();
    doc.fontSize(24).fillColor("#4B0082").text("Thank You!", { align: "center" });
    doc.moveDown(1);
    doc.fontSize(14).fillColor("#000").text("This pitch deck was AI-generated by VentureLens 🚀", {
      align: "center",
    });

    doc.end();
  } catch (err) {
    console.error("❌ Error generating pitch deck:", err);
    res.status(500).json({ message: "Failed to generate PDF" });
  }
};
